services:
  - type: web
    name: rizehvac
    runtime: node
    region: oregon
    plan: starter
    branch: main
    rootDir: .
    buildCommand: npm install && npm run build
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
